// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/4/2025, 3:31:49 pm
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/plugins/**/*.{js,ts,mjs}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/composables/**/*.{js,ts,mjs}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/utils/**/*.{js,ts,mjs}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/manas/Documents/_1/work/job search/projects/dev-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;